<a href="https://colab.research.google.com/github/Kushcodingexe/Data-Science-FDS-Course/blob/main/Kush_Sahni_2210110371_FDS_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

1. Create a NumPy array of shape (4,5) filled with zeros.

In [ ]:
zeros_4x5 = np.zeros((4, 5))
print("1) zeros_4x5:\n", zeros_4x5, "\n")

1) zeros_4x5:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 



2. For a given numpy array, print the number of dimensions, shape, and size of array.


In [ ]:
a = np.array([[1,2,3],[4,5,6]])   # example array
print("2) array a:\n", a)
print("   ndim:", a.ndim)
print("   shape:", a.shape)
print("   size (total elements):", a.size, "\n")

2) array a:
 [[1 2 3]
 [4 5 6]]
   ndim: 2
   shape: (2, 3)
   size (total elements): 6 



3. Generate a 1D NumPy array of 36 elements from 1 to 36 and reshape it into (3,4,3).

In [ ]:
one_to_36 = np.arange(1, 37)         # 1..36 inclusive
reshaped = one_to_36.reshape((3, 4, 3))
print("3) reshaped.shape =", reshaped.shape)
print(reshaped)

3) reshaped.shape = (3, 4, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]


4. Create a NumPy array of shape (3,4) with all elements equal to 9.

In [ ]:
nines_3x4 = np.full((3, 4), 9)
print("4) nines_3x4:\n", nines_3x4, "\n")

4) nines_3x4:
 [[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]] 



5. For a given two-dimensional array (4x4), extract the third column as a separate 1D array.

In [ ]:
arr_4x4 = np.arange(1, 17).reshape((4, 4))   # example 4x4
third_col_1d = arr_4x4[:, 2]                 # column index 2 is the "third" (0-based)
print("5) arr_4x4:\n", arr_4x4)
print("   third_col_1d:", third_col_1d, "\n")

5) arr_4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
   third_col_1d: [ 3  7 11 15] 



6. Calculate the sum of all elements in a (4x4) random integer NumPy array.

In [ ]:
rand_4x4 = np.random.randint(low=0, high=100, size=(4, 4))
total_sum = rand_4x4.sum()
print("6) rand_4x4:\n", rand_4x4)
print("   total_sum:", total_sum, "\n")

6) rand_4x4:
 [[65 16 92 92]
 [89 10 47 65]
 [55 12 91 62]
 [67 70 63 95]]
   total_sum: 991 



7. Given two NumPy arrays, perform element-wise addition, subtraction, and multiplication.

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
add = A + B
sub = A - B
mul = A * B           # element-wise multiply
print("7) A:\n", A)
print("   B:\n", B)
print("   A + B:\n", add)
print("   A - B:\n", sub)
print("   A * B (element-wise):\n", mul, "\n")

7) A:
 [[1 2]
 [3 4]]
   B:
 [[10 20]
 [30 40]]
   A + B:
 [[11 22]
 [33 44]]
   A - B:
 [[ -9 -18]
 [-27 -36]]
   A * B (element-wise):
 [[ 10  40]
 [ 90 160]] 



8. Compute the transpose of a matrix and verify its shape.

In [ ]:
M = np.array([[1,2,3],[4,5,6]])
M_T = M.T
print("8) M.shape =", M.shape, " M_T.shape =", M_T.shape)
print("   M:\n", M)
print("   M_T:\n", M_T)

8) M.shape = (2, 3)  M_T.shape = (3, 2)
   M:
 [[1 2 3]
 [4 5 6]]
   M_T:
 [[1 4]
 [2 5]
 [3 6]]


Pandas Section

In [ ]:
from IPython.display import display
csv_path = "ds_salaries.csv"   # https://www.kaggle.com/datasets/ruchi798/data-science-job-salaries?resource=download
df = pd.read_csv(csv_path, low_memory=False)
print("Loaded:", csv_path, " — shape:", df.shape)
print()



Loaded: ds_salaries.csv  — shape: (607, 12)



9. Display the first 10 rows

In [ ]:
print("=== 9) First 10 rows ===")
display(df.head(10))
print()

=== 9) First 10 rows ===


Unnamed: 0  work_year experience_level employment_type  \
0           0       2020               MI              FT   
1           1       2020               SE              FT   
2           2       2020               SE              FT   
3           3       2020               MI              FT   
4           4       2020               SE              FT   
5           5       2020               EN              FT   
6           6       2020               SE              FT   
7           7       2020               MI              FT   
8           8       2020               MI              FT   
9           9       2020               SE              FT   

                    job_title    salary salary_currency  salary_in_usd  \
0              Data Scientist     70000             EUR          79833   
1  Machine Learning Scientist    260000             USD         260000   
2           Big Data Engineer     85000             GBP         109024   
3        Product Data Analyst     20000             USD          20000   
4   Machine Learning Engineer    150000             USD         150000   
5                Data Analyst     72000             USD          72000   
6         Lead Data Scientist    190000             USD         190000   
7              Data Scientist  11000000             HUF          35735   
8       Business Data Analyst    135000             USD         135000   
9          Lead Data Engineer    125000             USD         125000   

  employee_residence  remote_ratio company_location company_size  
0                 DE             0               DE            L  
1                 JP             0               JP            S  
2                 GB            50               GB            M  
3                 HN             0               HN            S  
4                 US            50               US            L  
5                 US           100               US            L  
6                 US           100               US            S  
7                 HU            50               HU            L  
8                 US           100               US            L  
9                 NZ            50               NZ            S

10. Print names of all columns and their data types

In [ ]:
print("=== 10) Columns and dtypes ===")
print(df.dtypes)
print()
print("Column list:", list(df.columns))
print()

=== 10) Columns and dtypes ===
Unnamed: 0             int64
work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

Column list: ['Unnamed: 0', 'work_year', 'experience_level', 'employment_type', 'job_title', 'salary', 'salary_currency', 'salary_in_usd', 'employee_residence', 'remote_ratio', 'company_location', 'company_size']



In [ ]:
# --- Helper: detect best salary column (prefer numeric USD column if present) ---
def detect_salary_column(df):
    candidates = [c for c in df.columns if any(k in c.lower() for k in ("salary","comp","convertedcomp","pay"))]
    # prefer salary_in_usd if present
    for pref in ("salary_in_usd", "salary_usd", "salary"):
        if pref in df.columns:
            return pref
    if candidates:
        return candidates[0]
    return None

salary_col = detect_salary_column(df)
print("Detected salary column:", salary_col)
print()

Detected salary column: salary_in_usd



11. Extract only the salary column and calculate its mean (and median, count)

In [ ]:
print("=== 11) Salary statistics ===")
if salary_col is None:
    print("No salary-like column detected. Available columns:", list(df.columns))
else:
    # Clean and convert to numeric (remove commas, convert to floats)
    salary_series = pd.to_numeric(df[salary_col].astype(str).str.replace(',', ''), errors='coerce')
    mean_salary = salary_series.mean(skipna=True)
    median_salary = salary_series.median(skipna=True)
    count_nonnull = salary_series.notna().sum()
    print(f"Column used: {salary_col}")
    print("Count (non-null):", count_nonnull)
    print("Mean:", mean_salary)
    print("Median:", median_salary)
    # add cleaned numeric salary to dataframe for later use
    df['_salary_numeric'] = salary_series
print()

=== 11) Salary statistics ===
Column used: salary_in_usd
Count (non-null): 607
Mean: 112297.86985172982
Median: 101570.0



12. Display all rows by applying some filters on columns

In [ ]:
# Example filters: remote_ratio == 100 (fully remote) AND salary_in_usd above median
print("=== 12) Filtered rows example (fully remote & salary above median) ===")
# Choose realistic columns if present
filters = []
if 'remote_ratio' in df.columns:
    filters.append(df['remote_ratio'] == 100)
# use numeric salary if available
if '_salary_numeric' in df.columns:
    median_val = df['_salary_numeric'].median(skipna=True)
    filters.append(df['_salary_numeric'] > median_val)

if filters:
    combined = filters[0]
    for f in filters[1:]:
        combined &= f
    filtered_df = df.loc[combined].copy()
    print("Filtered shape:", filtered_df.shape)
    # show all rows of the filtered result — careful with very large results
    pd.set_option('display.max_rows', None)   # temporarily show all rows (use with caution)
    display(filtered_df)
    pd.reset_option('display.max_rows')
else:
    print("No appropriate columns found to demonstrate the filter. Available columns:", list(df.columns))
print()

=== 12) Filtered rows example (fully remote & salary above median) ===
Filtered shape: (222, 13)


Unnamed: 0  work_year experience_level employment_type  \
6             6       2020               SE              FT   
8             8       2020               MI              FT   
17           17       2020               SE              FT   
25           25       2020               EX              FT   
36           36       2020               MI              FT   
39           39       2020               EN              FT   
43           43       2020               MI              FT   
47           47       2020               SE              FT   
48           48       2020               MI              FT   
55           55       2020               SE              FT   
57           57       2020               MI              FT   
59           59       2020               MI              FT   
60           60       2020               MI              FT   
61           61       2020               MI              FT   
63           63       2020               SE              FT   
67           67       2020               SE              FT   
68           68       2020               EN              FT   
73           73       2021               EX              FT   
74           74       2021               EX              FT   
78           78       2021               MI              CT   
81           81       2021               MI              FT   
84           84       2021               EX              FT   
87           87       2021               MI              FT   
88           88       2021               SE              FT   
97           97       2021               MI              FT   
101         101       2021               SE              FT   
106         106       2021               MI              FT   
107         107       2021               SE              FT   
108         108       2021               SE              FT   
111         111       2021               SE              FT   
112         112       2021               SE              FT   
115         115       2021               EN              FT   
119         119       2021               MI              FT   
121         121       2021               SE              FT   
125         125       2021               MI              FT   
140         140       2021               MI              FT   
148         148       2021               SE              FT   
149         149       2021               SE              FT   
151         151       2021               MI              FT   
154         154       2021               SE              FT   
156         156       2021               MI              FT   
158         158       2021               SE              FT   
159         159       2021               EN              FT   
165         165       2021               SE              FT   
169         169       2021               MI              FT   
170         170       2021               MI              FT   
173         173       2021               SE              FT   
175         175       2021               SE              FT   
190         190       2021               SE              FT   
193         193       2021               SE              FT   
201         201       2021               SE              FT   
204         204       2021               MI              FT   
206         206       2021               SE              FT   
215         215       2021               SE              FT   
219         219       2021               SE              FT   
224         224       2021               SE              FT   
225         225       2021               EX              CT   
231         231       2021               SE              FT   
232         232       2021               SE              FT   
233         233       2021               SE              FT   
234         234       2021               MI              FT   
240         240       2021               SE              FT   
242         242       2021          

13. Select rows from index 10 to 20 and display only specific columns

In [ ]:
print("=== 13) Rows index 10..20 with specific columns ===")
# Example columns (choose ones that typically exist)
example_cols = []
for c in ('work_year', 'experience_level', 'job_title', salary_col, 'salary_currency', 'employee_residence', 'company_size'):
    if c in df.columns or c == salary_col:
        example_cols.append(c)
# fallback to first 4 columns if none of the above are present
if not example_cols:
    example_cols = list(df.columns[:4])
subset_10_20 = df.iloc[10:21][example_cols]
display(subset_10_20)
print()

=== 13) Rows index 10..20 with specific columns ===


work_year experience_level                  job_title  salary_in_usd  \
10       2020               EN             Data Scientist          51321   
11       2020               MI             Data Scientist          40481   
12       2020               EN             Data Scientist          39916   
13       2020               MI          Lead Data Analyst          87000   
14       2020               MI               Data Analyst          85000   
15       2020               MI               Data Analyst           8000   
16       2020               EN              Data Engineer          41689   
17       2020               SE          Big Data Engineer         114047   
18       2020               EN    Data Science Consultant           5707   
19       2020               MI         Lead Data Engineer          56000   
20       2020               MI  Machine Learning Engineer          43331   

   salary_currency employee_residence company_size  
10             EUR                 FR            S  
11             INR                 IN            L  
12             EUR                 FR            M  
13             USD                 US            L  
14             USD                 US            L  
15             USD                 PK            L  
16             JPY                 JP            S  
17             EUR                 PL            S  
18             INR                 IN            M  
19             USD                 PT            M  
20             CNY                 CN            M

14. Replace values of a column when specific criteria are met

In [ ]:
# Example 1: Create/replace a 'pay_bracket' column marking top 10% as 'Top10%'
# Example 2: Replace short company_size codes with full labels (S->Small, M->Medium, L->Large)
print("=== 14) Replace values example ===")
if '_salary_numeric' in df.columns:
    thresh_90 = df['_salary_numeric'].quantile(0.90)
    df['pay_bracket'] = np.where(df['_salary_numeric'] >= thresh_90, 'Top10%', 'Normal')
    print("Added 'pay_bracket' based on top 10% threshold:", thresh_90)
    print(df['pay_bracket'].value_counts(dropna=False))
else:
    print("No numeric salary available; skipping pay_bracket example.")

# Replace company_size shorthand if present
if 'company_size' in df.columns:
    mapping = {'S': 'Small', 'M': 'Medium', 'L': 'Large'}
    # Use map with fillna to keep any unusual values unchanged
    df['company_size_full'] = df['company_size'].map(mapping).fillna(df['company_size'])
    print("Created 'company_size_full' with readable sizes. Sample:")
    display(df[['company_size', 'company_size_full']].head(10))
else:
    print("No 'company_size' column found; skipping that replacement example.")
print()

=== 14) Replace values example ===
Added 'pay_bracket' based on top 10% threshold: 200000.0
pay_bracket
Normal    543
Top10%     64
Name: count, dtype: int64
Created 'company_size_full' with readable sizes. Sample:


company_size company_size_full
0            L             Large
1            S             Small
2            M            Medium
3            S             Small
4            L             Large
5            L             Large
6            S             Small
7            L             Large
8            L             Large
9            S             Small

15. Sort the DataFrame by one column ascending and then by another column descending

In [ ]:
# Example: sort by 'employee_residence' (asc) then by salary numeric (desc)
print("=== 15) Sorting example ===")
sort_by = []
ascending = []
if 'employee_residence' in df.columns:
    sort_by.append('employee_residence'); ascending.append(True)
if '_salary_numeric' in df.columns:
    sort_by.append('_salary_numeric'); ascending.append(False)

if sort_by:
    sorted_df = df.sort_values(by=sort_by, ascending=ascending, na_position='last')
    print(f"Sorted by {sort_by} with ascending={ascending}. Showing top 20 rows:")
    display(sorted_df.head(20)[['employee_residence', '_salary_numeric', 'job_title', 'company_size_full'] if 'job_title' in df.columns else sorted_df.columns[:5]])
else:
    print("No suitable columns found to demonstrate sorting. Columns:", list(df.columns)[:10])

# --- Optional: Save modified DataFrame to a new CSV if you want to keep the changes ---
out_path = "ds_salaries_processed.csv"
df.to_csv(out_path, index=False)
print("\nSaved processed DataFrame to:", out_path)

=== 15) Sorting example ===
Sorted by ['employee_residence', '_salary_numeric'] with ascending=[True, False]. Showing top 20 rows:


employee_residence  _salary_numeric                           job_title  \
480                 AE           120000           Machine Learning Engineer   
24                  AE           115000                 Lead Data Scientist   
481                 AE            65000           Machine Learning Engineer   
417                 AR            60000               Data Science Engineer   
69                  AT            91237                      Data Scientist   
35                  AT            74130                       Data Engineer   
507                 AT            64849                  Research Scientist   
510                 AU           150000   Computer Vision Software Engineer   
503                 AU            87425           Machine Learning Engineer   
505                 AU            86703                      Data Scientist   
218                 BE            88654           Machine Learning Engineer   
145                 BE            82744           Machine Learning Engineer   
89                  BG            80000                        Data Analyst   
506                 BO            75000  Applied Machine Learning Scientist   
149                 BR           160000                 Cloud Data Engineer   
494                 BR           100000                      Data Scientist   
133                 BR            24000            Computer Vision Engineer   
271                 BR            18907            Computer Vision Engineer   
205                 BR            12901                      Data Scientist   
96                  BR            12000                        AI Scientist   

    company_size_full  
480             Small  
24              Large  
481             Small  
417             Large  
69              Small  
35              Large  
507             Large  
510             Small  
503             Large  
505            Medium  
218            Medium  
145            Medium  
89              Small  
506             Large  
149             Small  
494            Medium  
133            Medium  
271            Medium  
205             Small  
96              Small


Saved processed DataFrame to: ds_salaries_processed.csv
